[package]
name = "reqwest-cookie-store"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cookie = "0"
cookie_store = "0"
reqwest = { version = ">=0.11", features = ['cookies'] }
